ESSENTIAL_INGREDIENTS = [
    "salt",
    "sugar",
    "butter",
    "water",
    "vegetable oil",
    "olive oil",
    "black pepper",
    "vanilla extract",
    "cinnamon",
    "powdered sugar",
    "paprika",
    "ice",
    "honey",
    "garlic salt",
    "balsamic vinegar",
    "red pepper",
    "kosher salt",
    "oregano",
    "cayenne",
    "baking soda",
    "chili powder"
    "white pepper"]